version: build-{build}

skip_tags: true

clone_depth: 1

branches:
  only:
    - master

environment:
  github_access_token:
    secure: +y38PLturiEnFo2khJ2YQNiIx1k2ToIjsbGhDiL/M6+cfAgjXxtWqWgeeGfKowuM
  github_email:
    secure: DYBh+dFLOZR/N9NsRd2UVdDoiGX+fcmXlg2GiRpBUJc=

install:
  - cinst docfx

build_script:
- ps: write-host "Nothing to build. Skipping..."

deploy_script:
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
- git config --global user.email %github_email%
- git config --global user.name "foxtrek64"
- bash releaseDocs.sh
