version: build-{build}

skip_tags: true

branches:
  only:
    - master

environment:
  github_access_token:
    secure: BXPoJU6XqzvaRKqI0w9n8xKoMnGKEv4MfoQNtMMP77G5cdpiYd31Ovjh3g551b8L
  github_email:
    secure: DYBh+dFLOZR/N9NsRd2UVdDoiGX+fcmXlg2GiRpBUJc=

install:
- cinst docfx
#  - dotnet tool install -g docfx --version 3.0.0-* --add-source https://www.myget.org/F/docfx-v3/api/v2
#  - git --version

build_script:
- ps: write-host "Nothing to build. Skipping..."

deploy_script:
- git config --global credential.helper store
- ps: Add-Content "$HOME\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
- git config --global user.email %github_email%
- git config --global user.name "Foxtrek64"
- git config http.postBuffer 524288000
- bash releaseDocs.sh
